version: "2.1"
services:
  blocky:
    image: spx01/blocky
    container_name: blocky-dns-app
    restart: unless-stopped
    hostname: blocky-dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./blocky-dns/config.yml:/app/config.yml