services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    hostname: memos
    restart: unless-stopped
    volumes:
      - ~/memos/:/var/opt/memos
    ports:
      - 5230:5230
    environment:
      - MEMOS_PASSWORD_AUTH=true
      - MEMOS_MODE=prod
      - MEMOS_ADDR=0.0.0.0