version: "3"

services:
  pihole:
    container_name: pihole
    hostname: pihole
    ports:
      - "53:53"
    environment:
      TZ: 'Europe/Helsinki'
    volumes:
      - './pihole:/etc/pihole'
      - './dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    image: pihole/pihole:latest