version: "3.3"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    hostname: vaultwarden
    restart: unless-stopped
    volumes:
    - ./vaultwarden-data/:/data/
    environment:
    - ADMIN_TOKEN=examplepassword(use bcrypt generator)
    - SIGNUPS_ALLOWED=false
