version: "3.3"

services:
  wg-easy:
    image: weejewel/wg-easy:latest
    container_name: wg-easy
    hostname: wg-easy
    ports:
      - "51821:51821/tcp" #Web GUI
      - "51820:51820/udp"
    environment:
      - WG_HOST=exmaple.host
      - PASSWORD=exmplepassword
    volumes:
      - ~/wg-easy-configs:/etc/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
